name: CI

on: [push, pull_request]

jobs:
  test:
    name: Test on Julia ${{ matrix.version }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        version:
          - '1.0'
          - '1.5'
        os:
          - ubuntu-latest
        arch:
          - x64
    steps:
      - name: Git checkout
        uses: actions/checkout@v2

      - name: Install Julia
        uses: julia-actions/setup-julia@latest
        with:
          version: ${{ matrix.version }}
          arch: ${{ matrix.arch }}

      - name: Build GenTeX.jl
        uses: julia-actions/julia-buildpkg@latest

        # Using the Nix package manager since the version of `dvisvgm` in Ubuntu is too old.
      - name: Cache install LaTeX
        uses: nix-actions/cache-install@v1.0.4
        with:
          key: nix-${{ hashFiles('latex.nix') }}
          nix_file: 'latex.nix'

      - name: Test
        uses: julia-actions/julia-runtest@latest

  docs:
    name: Make Documentation
    runs-on: ubuntu-latest
    steps:
      - name: Git checkout
        uses: actions/checkout@v2

      - name: Install Julia
        uses: julia-actions/setup-julia@latest

      - name: Install dependencies for docs
        run: julia --project=docs/ -e 'using Pkg; Pkg.develop(PackageSpec(path=pwd())); Pkg.instantiate()'

      - name: Make docs
        run: julia --project=docs/ docs/make.jl
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          DOCUMENTER_KEY: ${{ secrets.DOCUMENTER_KEY }}
