name: test

on: [push, pull_request]

jobs:
  test:
    name: Julia ${{ matrix.version }} - ${{ matrix.os }} - ${{ matrix.arch }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        version:
          - '1.5'
        os:
          - ubuntu-latest
        arch:
          - x64
    steps:
      - name: Git checkout
        uses: actions/checkout@v2

      - name: Install Julia
        uses: julia-actions/setup-julia@latest
        with:
          version: ${{ matrix.version }}
          arch: ${{ matrix.arch }}

      - name: Build GenTeX.jl
        uses: julia-actions/julia-buildpkg@latest

        # Using the Nix package manager since the version of `dvisvgm` in Ubuntu is too old.
      - name: Cache install LaTeX
        uses: nix-actions/cache-install@v1.0.4
        with:
          key: nix-${{ hashFiles('latex.nix') }}
          nix_file: 'latex.nix'

      - name: Test
        uses: julia-actions/julia-runtest@latest
